name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "👋 Welcome to our community! We're excited to see your first issue. Please provide details and we'll assist you."
        pr-message: "🚀 Thank you for your first pull request! We're here to help you get started with your contribution."
